
#include <c-lexer.h>

G_Terminal lang_lexer(PScanner *S) {
    G_Terminal term = -1;
    unsigned int seen_accepting_state = 0;
    int cc, nc = 0, pnc = 0;
    scanner_skip(S, &isspace);
    scanner_mark_lexeme_start(S);
state_0:
    if(!(cc = scanner_advance(S))) { goto undo_and_commit; }
    ++nc;
    switch(cc) {
        case 33: goto state_2;
        case 34: goto state_9;
        case 35: goto state_2;
        case 36: goto state_2;
        case 40: goto state_8;
        case 41: goto state_7;
        case 42: goto state_2;
        case 43: goto state_2;
        case 45: goto state_6;
        case 46: goto state_2;
        case 47: goto state_2;
        case 48: goto state_5;
        case 49: goto state_5;
        case 50: goto state_5;
        case 51: goto state_5;
        case 52: goto state_5;
        case 53: goto state_5;
        case 54: goto state_5;
        case 55: goto state_5;
        case 56: goto state_5;
        case 57: goto state_5;
        case 58: goto state_2;
        case 60: goto state_2;
        case 61: goto state_2;
        case 62: goto state_2;
        case 63: goto state_2;
        case 65: goto state_4;
        case 66: goto state_4;
        case 67: goto state_4;
        case 68: goto state_4;
        case 69: goto state_4;
        case 70: goto state_4;
        case 71: goto state_4;
        case 72: goto state_4;
        case 73: goto state_4;
        case 74: goto state_4;
        case 75: goto state_4;
        case 76: goto state_4;
        case 77: goto state_4;
        case 78: goto state_4;
        case 79: goto state_4;
        case 80: goto state_4;
        case 81: goto state_4;
        case 82: goto state_4;
        case 83: goto state_4;
        case 84: goto state_4;
        case 85: goto state_4;
        case 86: goto state_4;
        case 87: goto state_4;
        case 88: goto state_4;
        case 89: goto state_4;
        case 90: goto state_4;
        case 94: goto state_2;
        case 95: goto state_2;
        case 97: goto state_2;
        case 98: goto state_2;
        case 99: goto state_2;
        case 100: goto state_3;
        case 101: goto state_2;
        case 102: goto state_2;
        case 103: goto state_2;
        case 104: goto state_2;
        case 105: goto state_2;
        case 106: goto state_2;
        case 107: goto state_2;
        case 108: goto state_2;
        case 109: goto state_2;
        case 110: goto state_2;
        case 111: goto state_2;
        case 112: goto state_2;
        case 113: goto state_2;
        case 114: goto state_2;
        case 115: goto state_2;
        case 116: goto state_2;
        case 117: goto state_2;
        case 118: goto state_2;
        case 119: goto state_2;
        case 120: goto state_2;
        case 121: goto state_2;
        case 122: goto state_2;
        case 124: goto state_1;
        default: goto undo_and_commit;
    }
state_1:
    term = 1;
    goto commit;
state_2:
    term = 7;
    pnc = nc;
    seen_accepting_state = 1;
    if(!(cc = scanner_advance(S))) { goto undo_and_commit; }
    ++nc;
    switch(cc) {
        case 33: goto state_2;
        case 35: goto state_2;
        case 36: goto state_2;
        case 42: goto state_2;
        case 43: goto state_2;
        case 45: goto state_2;
        case 46: goto state_2;
        case 47: goto state_2;
        case 48: goto state_2;
        case 49: goto state_2;
        case 50: goto state_2;
        case 51: goto state_2;
        case 52: goto state_2;
        case 53: goto state_2;
        case 54: goto state_2;
        case 55: goto state_2;
        case 56: goto state_2;
        case 57: goto state_2;
        case 58: goto state_2;
        case 60: goto state_2;
        case 61: goto state_2;
        case 62: goto state_2;
        case 63: goto state_2;
        case 65: goto state_2;
        case 66: goto state_2;
        case 67: goto state_2;
        case 68: goto state_2;
        case 69: goto state_2;
        case 70: goto state_2;
        case 71: goto state_2;
        case 72: goto state_2;
        case 73: goto state_2;
        case 74: goto state_2;
        case 75: goto state_2;
        case 76: goto state_2;
        case 77: goto state_2;
        case 78: goto state_2;
        case 79: goto state_2;
        case 80: goto state_2;
        case 81: goto state_2;
        case 82: goto state_2;
        case 83: goto state_2;
        case 84: goto state_2;
        case 85: goto state_2;
        case 86: goto state_2;
        case 87: goto state_2;
        case 88: goto state_2;
        case 89: goto state_2;
        case 90: goto state_2;
        case 94: goto state_2;
        case 95: goto state_2;
        case 97: goto state_2;
        case 98: goto state_2;
        case 99: goto state_2;
        case 100: goto state_2;
        case 101: goto state_2;
        case 102: goto state_2;
        case 103: goto state_2;
        case 104: goto state_2;
        case 105: goto state_2;
        case 106: goto state_2;
        case 107: goto state_2;
        case 108: goto state_2;
        case 109: goto state_2;
        case 110: goto state_2;
        case 111: goto state_2;
        case 112: goto state_2;
        case 113: goto state_2;
        case 114: goto state_2;
        case 115: goto state_2;
        case 116: goto state_2;
        case 117: goto state_2;
        case 118: goto state_2;
        case 119: goto state_2;
        case 120: goto state_2;
        case 121: goto state_2;
        case 122: goto state_2;
        default: goto undo_and_commit;
    }
state_3:
    term = 7;
    pnc = nc;
    seen_accepting_state = 1;
    if(!(cc = scanner_advance(S))) { goto undo_and_commit; }
    ++nc;
    switch(cc) {
        case 55: goto state_2;
        case 56: goto state_2;
        case 57: goto state_2;
        case 58: goto state_2;
        case 60: goto state_2;
        case 61: goto state_2;
        case 62: goto state_2;
        case 63: goto state_2;
        case 65: goto state_2;
        case 66: goto state_2;
        case 67: goto state_2;
        case 68: goto state_2;
        case 69: goto state_2;
        case 70: goto state_2;
        case 71: goto state_2;
        case 72: goto state_2;
        case 73: goto state_2;
        case 74: goto state_2;
        case 75: goto state_2;
        case 76: goto state_2;
        case 77: goto state_2;
        case 78: goto state_2;
        case 79: goto state_2;
        case 80: goto state_2;
        case 81: goto state_2;
        case 82: goto state_2;
        case 83: goto state_2;
        case 84: goto state_2;
        case 85: goto state_2;
        case 86: goto state_2;
        case 87: goto state_2;
        case 88: goto state_2;
        case 89: goto state_2;
        case 90: goto state_2;
        case 94: goto state_2;
        case 95: goto state_2;
        case 97: goto state_2;
        case 98: goto state_2;
        case 99: goto state_2;
        case 100: goto state_2;
        case 101: goto state_14;
        case 102: goto state_2;
        case 103: goto state_2;
        case 104: goto state_2;
        case 105: goto state_2;
        case 106: goto state_2;
        case 107: goto state_2;
        case 108: goto state_2;
        case 109: goto state_2;
        case 110: goto state_2;
        case 111: goto state_2;
        case 112: goto state_2;
        case 113: goto state_2;
        case 114: goto state_2;
        case 115: goto state_2;
        case 116: goto state_2;
        case 117: goto state_2;
        case 118: goto state_2;
        case 119: goto state_2;
        case 120: goto state_2;
        case 121: goto state_2;
        case 122: goto state_2;
        case 33: goto state_2;
        case 35: goto state_2;
        case 36: goto state_2;
        case 42: goto state_2;
        case 43: goto state_2;
        case 45: goto state_2;
        case 46: goto state_2;
        case 47: goto state_2;
        case 48: goto state_2;
        case 49: goto state_2;
        case 50: goto state_2;
        case 51: goto state_2;
        case 52: goto state_2;
        case 53: goto state_2;
        case 54: goto state_2;
        default: goto undo_and_commit;
    }
state_4:
    term = 4;
    pnc = nc;
    seen_accepting_state = 1;
    if(!(cc = scanner_advance(S))) { goto undo_and_commit; }
    ++nc;
    switch(cc) {
        case 45: goto state_4;
        case 48: goto state_4;
        case 49: goto state_4;
        case 50: goto state_4;
        case 51: goto state_4;
        case 52: goto state_4;
        case 53: goto state_4;
        case 54: goto state_4;
        case 55: goto state_4;
        case 56: goto state_4;
        case 57: goto state_4;
        case 65: goto state_4;
        case 66: goto state_4;
        case 67: goto state_4;
        case 68: goto state_4;
        case 69: goto state_4;
        case 70: goto state_4;
        case 71: goto state_4;
        case 72: goto state_4;
        case 73: goto state_4;
        case 74: goto state_4;
        case 75: goto state_4;
        case 76: goto state_4;
        case 77: goto state_4;
        case 78: goto state_4;
        case 79: goto state_4;
        case 80: goto state_4;
        case 81: goto state_4;
        case 82: goto state_4;
        case 83: goto state_4;
        case 84: goto state_4;
        case 85: goto state_4;
        case 86: goto state_4;
        case 87: goto state_4;
        case 88: goto state_4;
        case 89: goto state_4;
        case 90: goto state_4;
        case 95: goto state_4;
        case 97: goto state_4;
        case 98: goto state_4;
        case 99: goto state_4;
        case 100: goto state_4;
        case 101: goto state_4;
        case 102: goto state_4;
        case 103: goto state_4;
        case 104: goto state_4;
        case 105: goto state_4;
        case 106: goto state_4;
        case 107: goto state_4;
        case 108: goto state_4;
        case 109: goto state_4;
        case 110: goto state_4;
        case 111: goto state_4;
        case 112: goto state_4;
        case 113: goto state_4;
        case 114: goto state_4;
        case 115: goto state_4;
        case 116: goto state_4;
        case 117: goto state_4;
        case 118: goto state_4;
        case 119: goto state_4;
        case 120: goto state_4;
        case 121: goto state_4;
        case 122: goto state_4;
        default: goto undo_and_commit;
    }
state_5:
    term = 6;
    pnc = nc;
    seen_accepting_state = 1;
    if(!(cc = scanner_advance(S))) { goto undo_and_commit; }
    ++nc;
    switch(cc) {
        case 48: goto state_5;
        case 49: goto state_5;
        case 50: goto state_5;
        case 51: goto state_5;
        case 52: goto state_5;
        case 53: goto state_5;
        case 54: goto state_5;
        case 55: goto state_5;
        case 56: goto state_5;
        case 57: goto state_5;
        default: goto undo_and_commit;
    }
state_6:
    term = 7;
    pnc = nc;
    seen_accepting_state = 1;
    if(!(cc = scanner_advance(S))) { goto undo_and_commit; }
    ++nc;
    switch(cc) {
        case 33: goto state_2;
        case 35: goto state_2;
        case 36: goto state_2;
        case 42: goto state_2;
        case 43: goto state_2;
        case 45: goto state_2;
        case 46: goto state_2;
        case 47: goto state_2;
        case 48: goto state_2;
        case 49: goto state_2;
        case 50: goto state_2;
        case 51: goto state_2;
        case 52: goto state_2;
        case 53: goto state_2;
        case 54: goto state_2;
        case 55: goto state_2;
        case 56: goto state_2;
        case 57: goto state_2;
        case 58: goto state_2;
        case 60: goto state_2;
        case 61: goto state_2;
        case 62: goto state_13;
        case 63: goto state_2;
        case 65: goto state_2;
        case 66: goto state_2;
        case 67: goto state_2;
        case 68: goto state_2;
        case 69: goto state_2;
        case 70: goto state_2;
        case 71: goto state_2;
        case 72: goto state_2;
        case 73: goto state_2;
        case 74: goto state_2;
        case 75: goto state_2;
        case 76: goto state_2;
        case 77: goto state_2;
        case 78: goto state_2;
        case 79: goto state_2;
        case 80: goto state_2;
        case 81: goto state_2;
        case 82: goto state_2;
        case 83: goto state_2;
        case 84: goto state_2;
        case 85: goto state_2;
        case 86: goto state_2;
        case 87: goto state_2;
        case 88: goto state_2;
        case 89: goto state_2;
        case 90: goto state_2;
        case 94: goto state_2;
        case 95: goto state_2;
        case 97: goto state_2;
        case 98: goto state_2;
        case 99: goto state_2;
        case 100: goto state_2;
        case 101: goto state_2;
        case 102: goto state_2;
        case 103: goto state_2;
        case 104: goto state_2;
        case 105: goto state_2;
        case 106: goto state_2;
        case 107: goto state_2;
        case 108: goto state_2;
        case 109: goto state_2;
        case 110: goto state_2;
        case 111: goto state_2;
        case 112: goto state_2;
        case 113: goto state_2;
        case 114: goto state_2;
        case 115: goto state_2;
        case 116: goto state_2;
        case 117: goto state_2;
        case 118: goto state_2;
        case 119: goto state_2;
        case 120: goto state_2;
        case 121: goto state_2;
        case 122: goto state_2;
        default: goto undo_and_commit;
    }
state_7:
    term = 2;
    goto commit;
state_8:
    term = 5;
    goto commit;
state_9:
    if(!(cc = scanner_advance(S))) { goto undo_and_commit; }
    ++nc;
    switch(cc) {
        case 81: goto state_9;
        case 82: goto state_9;
        case 83: goto state_9;
        case 84: goto state_9;
        case 85: goto state_9;
        case 86: goto state_9;
        case 87: goto state_9;
        case 88: goto state_9;
        case 89: goto state_9;
        case 90: goto state_9;
        case 91: goto state_9;
        case 92: goto state_10;
        case 93: goto state_9;
        case 94: goto state_9;
        case 95: goto state_9;
        case 96: goto state_9;
        case 97: goto state_9;
        case 98: goto state_9;
        case 99: goto state_9;
        case 100: goto state_9;
        case 101: goto state_9;
        case 102: goto state_9;
        case 103: goto state_9;
        case 104: goto state_9;
        case 105: goto state_9;
        case 106: goto state_9;
        case 107: goto state_9;
        case 108: goto state_9;
        case 109: goto state_9;
        case 110: goto state_9;
        case 111: goto state_9;
        case 112: goto state_9;
        case 113: goto state_9;
        case 114: goto state_9;
        case 115: goto state_9;
        case 116: goto state_9;
        case 117: goto state_9;
        case 118: goto state_9;
        case 119: goto state_9;
        case 120: goto state_9;
        case 121: goto state_9;
        case 122: goto state_9;
        case 123: goto state_9;
        case 124: goto state_9;
        case 125: goto state_9;
        case 126: goto state_9;
        case 127: goto state_9;
        case 0: goto state_9;
        case 1: goto state_9;
        case 2: goto state_9;
        case 3: goto state_9;
        case 4: goto state_9;
        case 5: goto state_9;
        case 6: goto state_9;
        case 7: goto state_9;
        case 8: goto state_9;
        case 9: goto state_9;
        case 10: goto state_9;
        case 11: goto state_9;
        case 12: goto state_9;
        case 13: goto state_9;
        case 14: goto state_9;
        case 15: goto state_9;
        case 16: goto state_9;
        case 17: goto state_9;
        case 18: goto state_9;
        case 19: goto state_9;
        case 20: goto state_9;
        case 21: goto state_9;
        case 22: goto state_9;
        case 23: goto state_9;
        case 24: goto state_9;
        case 25: goto state_9;
        case 26: goto state_9;
        case 27: goto state_9;
        case 28: goto state_9;
        case 29: goto state_9;
        case 30: goto state_9;
        case 31: goto state_9;
        case 32: goto state_9;
        case 33: goto state_9;
        case 34: goto state_11;
        case 35: goto state_9;
        case 36: goto state_9;
        case 37: goto state_9;
        case 38: goto state_9;
        case 39: goto state_9;
        case 40: goto state_9;
        case 41: goto state_9;
        case 42: goto state_9;
        case 43: goto state_9;
        case 44: goto state_9;
        case 45: goto state_9;
        case 46: goto state_9;
        case 47: goto state_9;
        case 48: goto state_9;
        case 49: goto state_9;
        case 50: goto state_9;
        case 51: goto state_9;
        case 52: goto state_9;
        case 53: goto state_9;
        case 54: goto state_9;
        case 55: goto state_9;
        case 56: goto state_9;
        case 57: goto state_9;
        case 58: goto state_9;
        case 59: goto state_9;
        case 60: goto state_9;
        case 61: goto state_9;
        case 62: goto state_9;
        case 63: goto state_9;
        case 64: goto state_9;
        case 65: goto state_9;
        case 66: goto state_9;
        case 67: goto state_9;
        case 68: goto state_9;
        case 69: goto state_9;
        case 70: goto state_9;
        case 71: goto state_9;
        case 72: goto state_9;
        case 73: goto state_9;
        case 74: goto state_9;
        case 75: goto state_9;
        case 76: goto state_9;
        case 77: goto state_9;
        case 78: goto state_9;
        case 79: goto state_9;
        case 80: goto state_9;
        default: goto undo_and_commit;
    }
state_10:
    if(!(cc = scanner_advance(S))) { goto undo_and_commit; }
    ++nc;
    switch(cc) {
        case 81: goto state_9;
        case 82: goto state_9;
        case 83: goto state_9;
        case 84: goto state_9;
        case 85: goto state_9;
        case 86: goto state_9;
        case 87: goto state_9;
        case 88: goto state_9;
        case 89: goto state_9;
        case 90: goto state_9;
        case 91: goto state_9;
        case 92: goto state_10;
        case 93: goto state_9;
        case 94: goto state_9;
        case 95: goto state_9;
        case 96: goto state_9;
        case 97: goto state_9;
        case 98: goto state_9;
        case 99: goto state_9;
        case 100: goto state_9;
        case 101: goto state_9;
        case 102: goto state_9;
        case 103: goto state_9;
        case 104: goto state_9;
        case 105: goto state_9;
        case 106: goto state_9;
        case 107: goto state_9;
        case 108: goto state_9;
        case 109: goto state_9;
        case 110: goto state_9;
        case 111: goto state_9;
        case 112: goto state_9;
        case 113: goto state_9;
        case 114: goto state_9;
        case 115: goto state_9;
        case 116: goto state_9;
        case 117: goto state_9;
        case 118: goto state_9;
        case 119: goto state_9;
        case 120: goto state_9;
        case 121: goto state_9;
        case 122: goto state_9;
        case 123: goto state_9;
        case 124: goto state_9;
        case 125: goto state_9;
        case 126: goto state_9;
        case 127: goto state_9;
        case 0: goto state_9;
        case 1: goto state_9;
        case 2: goto state_9;
        case 3: goto state_9;
        case 4: goto state_9;
        case 5: goto state_9;
        case 6: goto state_9;
        case 7: goto state_9;
        case 8: goto state_9;
        case 9: goto state_9;
        case 10: goto state_9;
        case 11: goto state_9;
        case 12: goto state_9;
        case 13: goto state_9;
        case 14: goto state_9;
        case 15: goto state_9;
        case 16: goto state_9;
        case 17: goto state_9;
        case 18: goto state_9;
        case 19: goto state_9;
        case 20: goto state_9;
        case 21: goto state_9;
        case 22: goto state_9;
        case 23: goto state_9;
        case 24: goto state_9;
        case 25: goto state_9;
        case 26: goto state_9;
        case 27: goto state_9;
        case 28: goto state_9;
        case 29: goto state_9;
        case 30: goto state_9;
        case 31: goto state_9;
        case 32: goto state_9;
        case 33: goto state_9;
        case 34: goto state_12;
        case 35: goto state_9;
        case 36: goto state_9;
        case 37: goto state_9;
        case 38: goto state_9;
        case 39: goto state_9;
        case 40: goto state_9;
        case 41: goto state_9;
        case 42: goto state_9;
        case 43: goto state_9;
        case 44: goto state_9;
        case 45: goto state_9;
        case 46: goto state_9;
        case 47: goto state_9;
        case 48: goto state_9;
        case 49: goto state_9;
        case 50: goto state_9;
        case 51: goto state_9;
        case 52: goto state_9;
        case 53: goto state_9;
        case 54: goto state_9;
        case 55: goto state_9;
        case 56: goto state_9;
        case 57: goto state_9;
        case 58: goto state_9;
        case 59: goto state_9;
        case 60: goto state_9;
        case 61: goto state_9;
        case 62: goto state_9;
        case 63: goto state_9;
        case 64: goto state_9;
        case 65: goto state_9;
        case 66: goto state_9;
        case 67: goto state_9;
        case 68: goto state_9;
        case 69: goto state_9;
        case 70: goto state_9;
        case 71: goto state_9;
        case 72: goto state_9;
        case 73: goto state_9;
        case 74: goto state_9;
        case 75: goto state_9;
        case 76: goto state_9;
        case 77: goto state_9;
        case 78: goto state_9;
        case 79: goto state_9;
        case 80: goto state_9;
        default: goto undo_and_commit;
    }
state_11:
    term = 8;
    goto commit;
state_12:
    term = 8;
    pnc = nc;
    seen_accepting_state = 1;
    if(!(cc = scanner_advance(S))) { goto undo_and_commit; }
    ++nc;
    switch(cc) {
        case 0: goto state_9;
        case 1: goto state_9;
        case 2: goto state_9;
        case 3: goto state_9;
        case 4: goto state_9;
        case 5: goto state_9;
        case 6: goto state_9;
        case 7: goto state_9;
        case 8: goto state_9;
        case 9: goto state_9;
        case 10: goto state_9;
        case 11: goto state_9;
        case 12: goto state_9;
        case 13: goto state_9;
        case 14: goto state_9;
        case 15: goto state_9;
        case 16: goto state_9;
        case 17: goto state_9;
        case 18: goto state_9;
        case 19: goto state_9;
        case 20: goto state_9;
        case 21: goto state_9;
        case 22: goto state_9;
        case 23: goto state_9;
        case 24: goto state_9;
        case 25: goto state_9;
        case 26: goto state_9;
        case 27: goto state_9;
        case 28: goto state_9;
        case 29: goto state_9;
        case 30: goto state_9;
        case 31: goto state_9;
        case 32: goto state_9;
        case 33: goto state_9;
        case 34: goto state_11;
        case 35: goto state_9;
        case 36: goto state_9;
        case 37: goto state_9;
        case 38: goto state_9;
        case 39: goto state_9;
        case 40: goto state_9;
        case 41: goto state_9;
        case 42: goto state_9;
        case 43: goto state_9;
        case 44: goto state_9;
        case 45: goto state_9;
        case 46: goto state_9;
        case 47: goto state_9;
        case 48: goto state_9;
        case 49: goto state_9;
        case 50: goto state_9;
        case 51: goto state_9;
        case 52: goto state_9;
        case 53: goto state_9;
        case 54: goto state_9;
        case 55: goto state_9;
        case 56: goto state_9;
        case 57: goto state_9;
        case 58: goto state_9;
        case 59: goto state_9;
        case 60: goto state_9;
        case 61: goto state_9;
        case 62: goto state_9;
        case 63: goto state_9;
        case 64: goto state_9;
        case 65: goto state_9;
        case 66: goto state_9;
        case 67: goto state_9;
        case 68: goto state_9;
        case 69: goto state_9;
        case 70: goto state_9;
        case 71: goto state_9;
        case 72: goto state_9;
        case 73: goto state_9;
        case 74: goto state_9;
        case 75: goto state_9;
        case 76: goto state_9;
        case 77: goto state_9;
        case 78: goto state_9;
        case 79: goto state_9;
        case 80: goto state_9;
        case 81: goto state_9;
        case 82: goto state_9;
        case 83: goto state_9;
        case 84: goto state_9;
        case 85: goto state_9;
        case 86: goto state_9;
        case 87: goto state_9;
        case 88: goto state_9;
        case 89: goto state_9;
        case 90: goto state_9;
        case 91: goto state_9;
        case 92: goto state_10;
        case 93: goto state_9;
        case 94: goto state_9;
        case 95: goto state_9;
        case 96: goto state_9;
        case 97: goto state_9;
        case 98: goto state_9;
        case 99: goto state_9;
        case 100: goto state_9;
        case 101: goto state_9;
        case 102: goto state_9;
        case 103: goto state_9;
        case 104: goto state_9;
        case 105: goto state_9;
        case 106: goto state_9;
        case 107: goto state_9;
        case 108: goto state_9;
        case 109: goto state_9;
        case 110: goto state_9;
        case 111: goto state_9;
        case 112: goto state_9;
        case 113: goto state_9;
        case 114: goto state_9;
        case 115: goto state_9;
        case 116: goto state_9;
        case 117: goto state_9;
        case 118: goto state_9;
        case 119: goto state_9;
        case 120: goto state_9;
        case 121: goto state_9;
        case 122: goto state_9;
        case 123: goto state_9;
        case 124: goto state_9;
        case 125: goto state_9;
        case 126: goto state_9;
        case 127: goto state_9;
        default: goto undo_and_commit;
    }
state_13:
    term = 3;
    pnc = nc;
    seen_accepting_state = 1;
    if(!(cc = scanner_advance(S))) { goto undo_and_commit; }
    ++nc;
    switch(cc) {
        case 33: goto state_2;
        case 35: goto state_2;
        case 36: goto state_2;
        case 42: goto state_2;
        case 43: goto state_2;
        case 45: goto state_2;
        case 46: goto state_2;
        case 47: goto state_2;
        case 48: goto state_2;
        case 49: goto state_2;
        case 50: goto state_2;
        case 51: goto state_2;
        case 52: goto state_2;
        case 53: goto state_2;
        case 54: goto state_2;
        case 55: goto state_2;
        case 56: goto state_2;
        case 57: goto state_2;
        case 58: goto state_2;
        case 60: goto state_2;
        case 61: goto state_2;
        case 62: goto state_2;
        case 63: goto state_2;
        case 65: goto state_2;
        case 66: goto state_2;
        case 67: goto state_2;
        case 68: goto state_2;
        case 69: goto state_2;
        case 70: goto state_2;
        case 71: goto state_2;
        case 72: goto state_2;
        case 73: goto state_2;
        case 74: goto state_2;
        case 75: goto state_2;
        case 76: goto state_2;
        case 77: goto state_2;
        case 78: goto state_2;
        case 79: goto state_2;
        case 80: goto state_2;
        case 81: goto state_2;
        case 82: goto state_2;
        case 83: goto state_2;
        case 84: goto state_2;
        case 85: goto state_2;
        case 86: goto state_2;
        case 87: goto state_2;
        case 88: goto state_2;
        case 89: goto state_2;
        case 90: goto state_2;
        case 94: goto state_2;
        case 95: goto state_2;
        case 97: goto state_2;
        case 98: goto state_2;
        case 99: goto state_2;
        case 100: goto state_2;
        case 101: goto state_2;
        case 102: goto state_2;
        case 103: goto state_2;
        case 104: goto state_2;
        case 105: goto state_2;
        case 106: goto state_2;
        case 107: goto state_2;
        case 108: goto state_2;
        case 109: goto state_2;
        case 110: goto state_2;
        case 111: goto state_2;
        case 112: goto state_2;
        case 113: goto state_2;
        case 114: goto state_2;
        case 115: goto state_2;
        case 116: goto state_2;
        case 117: goto state_2;
        case 118: goto state_2;
        case 119: goto state_2;
        case 120: goto state_2;
        case 121: goto state_2;
        case 122: goto state_2;
        default: goto undo_and_commit;
    }
state_14:
    term = 7;
    pnc = nc;
    seen_accepting_state = 1;
    if(!(cc = scanner_advance(S))) { goto undo_and_commit; }
    ++nc;
    switch(cc) {
        case 33: goto state_2;
        case 35: goto state_2;
        case 36: goto state_2;
        case 42: goto state_2;
        case 43: goto state_2;
        case 45: goto state_2;
        case 46: goto state_2;
        case 47: goto state_2;
        case 48: goto state_2;
        case 49: goto state_2;
        case 50: goto state_2;
        case 51: goto state_2;
        case 52: goto state_2;
        case 53: goto state_2;
        case 54: goto state_2;
        case 55: goto state_2;
        case 56: goto state_2;
        case 57: goto state_2;
        case 58: goto state_2;
        case 60: goto state_2;
        case 61: goto state_2;
        case 62: goto state_2;
        case 63: goto state_2;
        case 65: goto state_2;
        case 66: goto state_2;
        case 67: goto state_2;
        case 68: goto state_2;
        case 69: goto state_2;
        case 70: goto state_2;
        case 71: goto state_2;
        case 72: goto state_2;
        case 73: goto state_2;
        case 74: goto state_2;
        case 75: goto state_2;
        case 76: goto state_2;
        case 77: goto state_2;
        case 78: goto state_2;
        case 79: goto state_2;
        case 80: goto state_2;
        case 81: goto state_2;
        case 82: goto state_2;
        case 83: goto state_2;
        case 84: goto state_2;
        case 85: goto state_2;
        case 86: goto state_2;
        case 87: goto state_2;
        case 88: goto state_2;
        case 89: goto state_2;
        case 90: goto state_2;
        case 94: goto state_2;
        case 95: goto state_2;
        case 97: goto state_2;
        case 98: goto state_2;
        case 99: goto state_2;
        case 100: goto state_2;
        case 101: goto state_2;
        case 102: goto state_15;
        case 103: goto state_2;
        case 104: goto state_2;
        case 105: goto state_2;
        case 106: goto state_2;
        case 107: goto state_2;
        case 108: goto state_2;
        case 109: goto state_2;
        case 110: goto state_2;
        case 111: goto state_2;
        case 112: goto state_2;
        case 113: goto state_2;
        case 114: goto state_2;
        case 115: goto state_2;
        case 116: goto state_2;
        case 117: goto state_2;
        case 118: goto state_2;
        case 119: goto state_2;
        case 120: goto state_2;
        case 121: goto state_2;
        case 122: goto state_2;
        default: goto undo_and_commit;
    }
state_15:
    term = 7;
    pnc = nc;
    seen_accepting_state = 1;
    if(!(cc = scanner_advance(S))) { goto undo_and_commit; }
    ++nc;
    switch(cc) {
        case 33: goto state_2;
        case 35: goto state_2;
        case 36: goto state_2;
        case 42: goto state_2;
        case 43: goto state_2;
        case 45: goto state_2;
        case 46: goto state_2;
        case 47: goto state_2;
        case 48: goto state_2;
        case 49: goto state_2;
        case 50: goto state_2;
        case 51: goto state_2;
        case 52: goto state_2;
        case 53: goto state_2;
        case 54: goto state_2;
        case 55: goto state_2;
        case 56: goto state_2;
        case 57: goto state_2;
        case 58: goto state_2;
        case 60: goto state_2;
        case 61: goto state_2;
        case 62: goto state_2;
        case 63: goto state_2;
        case 65: goto state_2;
        case 66: goto state_2;
        case 67: goto state_2;
        case 68: goto state_2;
        case 69: goto state_2;
        case 70: goto state_2;
        case 71: goto state_2;
        case 72: goto state_2;
        case 73: goto state_2;
        case 74: goto state_2;
        case 75: goto state_2;
        case 76: goto state_2;
        case 77: goto state_2;
        case 78: goto state_2;
        case 79: goto state_2;
        case 80: goto state_2;
        case 81: goto state_2;
        case 82: goto state_2;
        case 83: goto state_2;
        case 84: goto state_2;
        case 85: goto state_2;
        case 86: goto state_2;
        case 87: goto state_2;
        case 88: goto state_2;
        case 89: goto state_2;
        case 90: goto state_2;
        case 94: goto state_2;
        case 95: goto state_2;
        case 97: goto state_2;
        case 98: goto state_2;
        case 99: goto state_2;
        case 100: goto state_2;
        case 101: goto state_2;
        case 102: goto state_2;
        case 103: goto state_2;
        case 104: goto state_2;
        case 105: goto state_2;
        case 106: goto state_2;
        case 107: goto state_2;
        case 108: goto state_2;
        case 109: goto state_2;
        case 110: goto state_2;
        case 111: goto state_2;
        case 112: goto state_2;
        case 113: goto state_2;
        case 114: goto state_2;
        case 115: goto state_2;
        case 116: goto state_2;
        case 117: goto state_16;
        case 118: goto state_2;
        case 119: goto state_2;
        case 120: goto state_2;
        case 121: goto state_2;
        case 122: goto state_2;
        default: goto undo_and_commit;
    }
state_16:
    term = 7;
    pnc = nc;
    seen_accepting_state = 1;
    if(!(cc = scanner_advance(S))) { goto undo_and_commit; }
    ++nc;
    switch(cc) {
        case 33: goto state_2;
        case 35: goto state_2;
        case 36: goto state_2;
        case 42: goto state_2;
        case 43: goto state_2;
        case 45: goto state_2;
        case 46: goto state_2;
        case 47: goto state_2;
        case 48: goto state_2;
        case 49: goto state_2;
        case 50: goto state_2;
        case 51: goto state_2;
        case 52: goto state_2;
        case 53: goto state_2;
        case 54: goto state_2;
        case 55: goto state_2;
        case 56: goto state_2;
        case 57: goto state_2;
        case 58: goto state_2;
        case 60: goto state_2;
        case 61: goto state_2;
        case 62: goto state_2;
        case 63: goto state_2;
        case 65: goto state_2;
        case 66: goto state_2;
        case 67: goto state_2;
        case 68: goto state_2;
        case 69: goto state_2;
        case 70: goto state_2;
        case 71: goto state_2;
        case 72: goto state_2;
        case 73: goto state_2;
        case 74: goto state_2;
        case 75: goto state_2;
        case 76: goto state_2;
        case 77: goto state_2;
        case 78: goto state_2;
        case 79: goto state_2;
        case 80: goto state_2;
        case 81: goto state_2;
        case 82: goto state_2;
        case 83: goto state_2;
        case 84: goto state_2;
        case 85: goto state_2;
        case 86: goto state_2;
        case 87: goto state_2;
        case 88: goto state_2;
        case 89: goto state_2;
        case 90: goto state_2;
        case 94: goto state_2;
        case 95: goto state_2;
        case 97: goto state_2;
        case 98: goto state_2;
        case 99: goto state_2;
        case 100: goto state_2;
        case 101: goto state_2;
        case 102: goto state_2;
        case 103: goto state_2;
        case 104: goto state_2;
        case 105: goto state_2;
        case 106: goto state_2;
        case 107: goto state_2;
        case 108: goto state_2;
        case 109: goto state_2;
        case 110: goto state_17;
        case 111: goto state_2;
        case 112: goto state_2;
        case 113: goto state_2;
        case 114: goto state_2;
        case 115: goto state_2;
        case 116: goto state_2;
        case 117: goto state_2;
        case 118: goto state_2;
        case 119: goto state_2;
        case 120: goto state_2;
        case 121: goto state_2;
        case 122: goto state_2;
        default: goto undo_and_commit;
    }
state_17:
    term = 0;
    pnc = nc;
    seen_accepting_state = 1;
    if(!(cc = scanner_advance(S))) { goto undo_and_commit; }
    ++nc;
    switch(cc) {
        case 113: goto state_2;
        case 114: goto state_2;
        case 115: goto state_2;
        case 116: goto state_2;
        case 117: goto state_2;
        case 118: goto state_2;
        case 119: goto state_2;
        case 120: goto state_2;
        case 121: goto state_2;
        case 122: goto state_2;
        case 33: goto state_2;
        case 35: goto state_2;
        case 36: goto state_2;
        case 42: goto state_2;
        case 43: goto state_2;
        case 45: goto state_2;
        case 46: goto state_2;
        case 47: goto state_2;
        case 48: goto state_2;
        case 49: goto state_2;
        case 50: goto state_2;
        case 51: goto state_2;
        case 52: goto state_2;
        case 53: goto state_2;
        case 54: goto state_2;
        case 55: goto state_2;
        case 56: goto state_2;
        case 57: goto state_2;
        case 58: goto state_2;
        case 60: goto state_2;
        case 61: goto state_2;
        case 62: goto state_2;
        case 63: goto state_2;
        case 65: goto state_2;
        case 66: goto state_2;
        case 67: goto state_2;
        case 68: goto state_2;
        case 69: goto state_2;
        case 70: goto state_2;
        case 71: goto state_2;
        case 72: goto state_2;
        case 73: goto state_2;
        case 74: goto state_2;
        case 75: goto state_2;
        case 76: goto state_2;
        case 77: goto state_2;
        case 78: goto state_2;
        case 79: goto state_2;
        case 80: goto state_2;
        case 81: goto state_2;
        case 82: goto state_2;
        case 83: goto state_2;
        case 84: goto state_2;
        case 85: goto state_2;
        case 86: goto state_2;
        case 87: goto state_2;
        case 88: goto state_2;
        case 89: goto state_2;
        case 90: goto state_2;
        case 94: goto state_2;
        case 95: goto state_2;
        case 97: goto state_2;
        case 98: goto state_2;
        case 99: goto state_2;
        case 100: goto state_2;
        case 101: goto state_2;
        case 102: goto state_2;
        case 103: goto state_2;
        case 104: goto state_2;
        case 105: goto state_2;
        case 106: goto state_2;
        case 107: goto state_2;
        case 108: goto state_2;
        case 109: goto state_2;
        case 110: goto state_2;
        case 111: goto state_2;
        case 112: goto state_2;
        default: goto undo_and_commit;
    }
undo_and_commit:
    if(!seen_accepting_state) {
        return -1;
    }
    scanner_pushback(S, nc - pnc);
commit:
    scanner_mark_lexeme_end(S);
    return term;
}
